### ISSUE TITLE
syntax-error catching what it shouldn't

### ISSUE THREAD

**Issue by darsain** [makojs/js#69]
I'm trying to build a `cli.js` of [xo](https://github.com/sindresorhus/xo) which has an out of function return statement, so I turn on the `allowReturnOutsideFunction` flag in acorn (passed via `options.detectiveOptions.parse`).

This is however rendered pointless by `syntax-error` in `check()` on [L85](https://github.com/makojs/js/blob/e2eaaaedbd6da1b0aa6165d2b05901b50e2766fc/index.js#L85), which throws `ParseError: 'return' outside of function`, and there's no way to silence it.

Why is this check even necessary? :)

**Comment by dominicbarnes** [comment]
Ah yeah, `syntax-check` was there to prevent builds from happening when you had bad syntax. I think it's still valuable, since running `detective()` on invalid syntax doesn't throw.

Since `syntax-error` just uses the `vm` module, and not parsing into an AST, it isn't nearly as configurable. Maybe I can just add a custom config to turn off syntax checking, as I don't think I want to remove it entirely.

**Comment by dominicbarnes** [comment]
As of v0.21.2, you can add `checkSyntax: false` to your config to disable this feature.
